#spring.application.name=eventplataform
#spring.datasource.url=jdbc:mariadb://localhost:3306/events
#spring.datasource.username=amairvidro
#spring.datasource.password=vitor13
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Configurações do banco em memória H2
spring.datasource.url=jdbc:h2:mem:eventosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Diz ao Hibernate para criar as tabelas automaticamente e usar o dialeto do H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Habilita uma interface visual no navegador para você ver as tabelas
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console