spring.application.name=eventplataform
spring.datasource.url=jdbc:mariadb://localhost:3306/events
spring.datasource.username=amairvidro
spring.datasource.password=vitor13
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
